# -*- coding: utf-8 -*-
"""SLM.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PPXA5HesC3kMfLoiXwuPR3AdWxi5zdhR
"""

# Code by Abasalt Bahrami - Feb 28, 2023

# Define a function to calculate the electric field of a Gaussian beam given its radial distance, propagation distance,
# beam waist size, wavenumber, and curvature radius

from scipy.special import jv
from diffractio.scalar_sources_XY import Scalar_source_XY
from diffractio import np, plt, sp
from diffractio import degrees, mm, nm, um
import cv2
import numpy as np
import matplotlib.pyplot as plt


def gaussian_beam(r, z, BeamSize, k, R):
    return (BeamSize * np.exp(-r**2/BeamSize**2)) * np.exp(1j * (k * z + k * r**2/2 * R))


# Set the parameters for the Gaussian beam
BeamSize = 200e-6  # Beam waist size in meters
wavelegth = 433e-9  # Wavelength of the beam in meters
k = 2 * np.pi / (wavelegth)  # Wavenumber of the beam
gridsize = 500e-6  # Size of the grid in meters
R = np.inf  # Curvature radius of the beam (infinity for a plane wave)

# Plot the Gaussian beam intensity profile in polar coordinates
fig, axs = plt.subplots(1, 4, figsize=(15, 5))
plt.subplot(1, 4, 3)
R, Z = np.meshgrid(np.linspace(-gridsize, gridsize, 100),
                   np.linspace(-gridsize, gridsize, 100))
intensity = np.abs(gaussian_beam(R, Z, BeamSize, k, R))**2
plt.imshow(intensity/np.max(intensity), cmap='gist_heat')
plt.xlabel('R (mm)')
plt.ylabel('Z (mm)')
plt.xticks([])
plt.yticks([])
plt.title("Gaussian Intensity")
plt.colorbar(shrink=0.15)

# Plot the Gaussian beam intensity profile in Cartesian coordinates

plt.subplot(1, 4, 2)
z = 0  # Position along the optical axis
R = np.inf  # Curvature radius of the beam (infinity for a plane wave)
X, Y = np.meshgrid(np.linspace(-gridsize, gridsize, 100),
                   np.linspace(-gridsize, gridsize, 100))
r = np.sqrt(X**2 + Y**2)
gaussian_beam = BeamSize * \
    np.exp(-r**2/BeamSize**2) * np.exp(1j * (k * z + k * r**2/2/R))
plt.imshow(np.abs(gaussian_beam**2/np.max(gaussian_beam**2)), cmap='gist_heat')
plt.xlabel('X (mm)')
plt.ylabel('Y (mm)')
plt.xticks([])
plt.yticks([])
plt.title('Gaussain Intensity')
plt.colorbar(shrink=0.15)


# Vortex Intensity Profile -- Cartesian
plt.subplot(1, 4, 4)  # create a subplot for the vortex intensity profile
X, Y = np.meshgrid(np.linspace(-gridsize, gridsize, 100),
                   np.linspace(-gridsize, gridsize, 100))  # create a grid of x and y values
R = np.sqrt(X**2 + Y**2)  # calculate the radial distance from the center
phi = np.arctan2(Y, X)  # calculate the azimuthal angle
charge = 1  # set the charge of the vortex
# create a phase mask for the vortex
VortexMask = R**charge * np.exp(1j * charge * phi)
# apply the phase mask to the Gaussian beam
VortexBeam = VortexMask*gaussian_beam
# display the intensity profile of the vortex beam
plt.imshow(np.abs((VortexBeam/np.max(VortexBeam))**2), cmap='gist_heat')
plt.xlabel('X (mm)')  # set the x-axis label
plt.ylabel('Y (mm)')  # set the y-axis label
plt.xticks([])  # remove the x-axis ticks
plt.yticks([])  # remove the y-axis ticks
plt.title('Vortex Intensity')  # set the title of the plot
plt.text(5, 10, "charge = " + str(charge), color='white',
         fontsize=13)  # add text to the plot
plt.colorbar(shrink=0.15)  # add a colorbar to the plot


# Vortex Mask Phase
plt.subplot(1, 4, 1)
plt.imshow(np.angle(VortexMask)/np.pi, cmap='magma')
plt.xlabel('X (mm)')
plt.ylabel('Y (mm)')
plt.title("Phase mask")
plt.xticks([])
plt.yticks([])
cb = plt.colorbar(ticks=[-0.99, 0, 0.99], shrink=0.15)
cb.set_ticklabels([r"$-\pi$", r"$0$", r"$\pi$"])
plt.show()


# Resize the mask to the desired size
resized_mask = cv2.resize(np.angle(VortexMask)/np.pi, (1920, 1152))

# Normalize the values to the range [0, 255] and convert to uint8 data type
normalized_mask = cv2.normalize(
    resized_mask, None, 0, 255, cv2.NORM_MINMAX, cv2.CV_8U)

# Save the mask as a grayscale bmp image
cv2.imwrite("/Users/abasaltbahrami/Downloads/vortex_mask1.bmp", normalized_mask)

# Phase returder


def calculate_thickness(phase_shift, wavelength, refractive_index):
    return (phase_shift * wavelength) / (2 * np.pi * refractive_index)


wavelength = 403e-9      # Wavelength of the wave in meters
refractive_index = 2.0   # Refractive index of the waveguide material

phase_shifts = np.linspace(0, 10, 1000)
thicknesses = calculate_thickness(
    phase_shifts * np.pi, wavelength, refractive_index)

plt.plot(phase_shifts, thicknesses * 1e6)
plt.xlabel('Phase Shift (π)')
plt.ylabel('Thickness (μm)')
plt.title('Thickness vs. Phase Shift')
plt.show()

# try using commands from this website: https://diffractio.readthedocs.io/en/latest/source/tutorial/scalar_XY/sources_xy.html


M = 7

x0 = np.linspace(-1 * mm, 1 * mm, 512)
y0 = np.linspace(-1 * mm, 1 * mm, 512)
wavelength = 0.444 * um

u = Scalar_source_XY(x=x0, y=y0, wavelength=wavelength)

ID1 = plt.figure(figsize=(12, 6))
plt.suptitle("$Vortex beams$", fontsize=20)

for m in range(M):
    u.vortex_beam(A=1, r0=(0 * um, 0 * um), w0=400 * um, m=m)
    intensity = np.abs(u.u)**2
    phase = np.angle(u.u) / degrees
    phase[intensity < 0.005] = 0

    # drawings
    title = "(%d)" % (m)
    plt.subplot(2, M, m + 1)
    plt.axis('off')
    plt.title(title)
    h1 = plt.imshow(intensity)
    h1.set_cmap("gist_heat")

    plt.subplot(2, M, m + M + 1)
    plt.axis('off')
    h2 = plt.imshow(phase)
    h2.set_cmap("twilight")

# Bessel functions
# I have to create these beam profiles from a Gaussian beam; A Bessel beam can be generated from a Gaussian beam by
# using a specific mathematical transformation known as a Hankel transform.
# Bessel beam profile will be after the objective


wavelength = 403e-9
k = 2 * np.pi / wavelength
R = np.inf
GridSize = 100e-8

X, Y = np.meshgrid(np.linspace(-GridSize, GridSize, 100),
                   np.linspace(-GridSize, GridSize, 100))
r = np.sqrt(X**2 + Y**2)

fig, axs = plt.subplots(1, 6, figsize=(15, 5))

for i, n in enumerate([0, 1, 2, 3, 4, 5]):
    BesselIntensity = np.abs(jv(n, k * r))**2
    axs[i].imshow(BesselIntensity / np.max(BesselIntensity),
                  extent=(-GridSize, GridSize, -GridSize, GridSize), cmap='gist_heat')
    axs[i].set_xlabel('X (mm)')
    axs[i].set_ylabel('Y (mm)')
    axs[i].set_xticks([])
    axs[i].set_yticks([])
    axs[i].set_title('Bessel Beam Intensity')
    axs[i].text(0.01, 0.99, f'n = {n}', transform=axs[i].transAxes,
                ha='left', va='top', fontsize=14, color='white')

plt.tight_layout()
plt.show()
